"""Detect auto-generated activity names, in French and English.

Garmin and Strava both name activities automatically when the athlete does
not: "Morning Run", "Course à pied le matin", "Maisod Randonnée". Those names
carry no information, so they must never overwrite a name the athlete chose.
The previous check only knew a handful of English words, which meant French
auto-names (the ones a French-locale Garmin actually produces) were treated as
meaningful and could overwrite a personalised Strava name.
"""
import re

# Sport words, longest first so "course à pied" wins over "course"
_ACTIVITY_WORDS = [
    "course à pied", "course a pied", "marche à pied", "marche a pied",
    "randonnée", "randonnee", "cyclisme", "natation", "musculation",
    "vélo", "velo", "marche", "course", "trail", "sortie",
    "weight training", "strength training", "open water swim",
    "running", "cycling", "walking", "swimming", "hiking", "rowing",
    "workout", "run", "ride", "walk", "swim", "hike", "row",
]

# Time-of-day markers
_TIME_WORDS_BEFORE = [  # English: "Morning Run"
    "morning", "afternoon", "evening", "night", "lunch", "midday",
]
_TIME_WORDS_AFTER = [  # French: "Course à pied le matin"
    "le matin", "en matinée", "en matinee", "le midi", "à midi", "a midi",
    "l'après-midi", "l'apres-midi", "de l'après-midi", "de l'apres-midi",
    "en soirée", "en soiree", "le soir", "la nuit", "de nuit",
]


def _group(words) -> str:
    return "(?:" + "|".join(re.escape(w) for w in words) + ")"


_ACT = _group(_ACTIVITY_WORDS)
_BEFORE = _group(_TIME_WORDS_BEFORE)
_AFTER = _group(_TIME_WORDS_AFTER)

_PATTERNS = [
    re.compile(rf"^{_ACT}$"),                 # "Running", "Course à pied"
    re.compile(rf"^{_BEFORE}\s+{_ACT}$"),     # "Morning Run", "Lunch Ride"
    re.compile(rf"^{_ACT}\s+{_AFTER}$"),      # "Course à pied le matin"
    re.compile(rf"^{_ACT}\s+{_BEFORE}$"),     # "Run morning" (rare)
    # "<lieu> <sport>": "Maisod Randonnée", "Paris Marche à pied",
    # "Clairvaux-les-Lacs Cyclisme". Only place-like prefixes: no digits and
    # no quote, which is what separates them from workout names such as
    # "45' Easy Run" or "1h20 Long Run".
    re.compile(rf"^[^\d'’\"]+\s+{_ACT}$"),
]


def is_auto_generated_name(name: str) -> bool:
    """True when the name looks auto-generated by Garmin or Strava.

    Matching is accent- and case-insensitive on the patterns above. An empty
    name counts as auto-generated: there is nothing to protect.
    """
    if not name or not name.strip():
        return True
    candidate = " ".join(name.strip().lower().split())
    return any(p.match(candidate) for p in _PATTERNS)
